modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/Gabalus/FracturedRealityCore/issues"

[[mods]]
modId="fractured_reality"
version="${file.jarVersion}"
displayName="Fractured Reality Core"
authors="Gabalus"
description='''
Progression and integration core for the Fractured Reality / Discords modpack.
'''

[[dependencies.fractured_reality]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fractured_reality]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fractured_reality]]
    modId="hyperbox"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
